/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.koder95.ip.marriage;

import java.awt.EventQueue;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import static pl.koder95.ip.Main.OPTION_ZA;
import pl.koder95.ip.ObjectNotFoundException;
import pl.koder95.ip.Person;

/**
 *
 * @author Kamil
 */
public class IndexResearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form Ochrzczeni
     */
    public IndexResearchFrame() {
        String file = indices.getFileName();
        super.setTitle(file.substring(0, file.length()-4));
        initComponents();
        MarriageIndex minIndex = indices.getFirst();
        MarriageIndex maxIndex = indices.getLast();
        setFooter(minIndex.getAct() + "/" + minIndex.year, maxIndex.getAct()
                + "/" + maxIndex.year);
        suggestScroll.setVisible(false);
        resetForm();
    }
    
    private final IndexBrowser indices = new IndexBrowser();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sex = new javax.swing.ButtonGroup();
        layers = new javax.swing.JLayeredPane();
        mainPanel = new javax.swing.JPanel();
        actNumberLabel = new javax.swing.JLabel();
        actNumber = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        footer = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        separator = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        maleInfoPanel = new javax.swing.JPanel();
        maleLastNameLabel = new javax.swing.JLabel();
        maleNameLabel = new javax.swing.JLabel();
        maleLastName = new javax.swing.JLabel();
        maleName = new javax.swing.JLabel();
        femaleInfoPanel = new javax.swing.JPanel();
        femaleLastNameLabel = new javax.swing.JLabel();
        femaleNameLabel = new javax.swing.JLabel();
        femaleLastName = new javax.swing.JLabel();
        femaleName = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        suggestPanel = new javax.swing.JPanel();
        suggestScroll = new javax.swing.JScrollPane();
        suggestList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(pl.koder95.ip.Main.FAVICON);
        setResizable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pl/koder95/ip/strings"); // NOI18N
        actNumberLabel.setText(bundle.getString("F_LABEL_ACT_NO")); // NOI18N

        actNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        yearLabel.setText(bundle.getString("F_LABEL_YEAR")); // NOI18N

        year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        searchLabel.setText(bundle.getString("F_LABEL_SEARCH")); // NOI18N

        search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchCaretUpdate(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        footer.setText(bundle.getString("F_FOOTER_TEXT_PART2")); // NOI18N

        min.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        separator.setText(bundle.getString("F_FOOTER_TEXT_PART4")); // NOI18N

        max.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        sex.add(male);
        male.setSelected(true);
        male.setText(bundle.getString("F_RADIO_BUTTON_MALE")); // NOI18N

        sex.add(female);
        female.setText(bundle.getString("F_RADIO_BUTTON_FEMALE")); // NOI18N

        maleInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("F_PANEL_HUSBAND"))); // NOI18N

        maleLastNameLabel.setText(bundle.getString("F_LABEL_LASTNAME")); // NOI18N

        maleNameLabel.setText(bundle.getString("F_LABEL_NAME")); // NOI18N

        maleLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        maleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout maleInfoPanelLayout = new javax.swing.GroupLayout(maleInfoPanel);
        maleInfoPanel.setLayout(maleInfoPanelLayout);
        maleInfoPanelLayout.setHorizontalGroup(
            maleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maleInfoPanelLayout.createSequentialGroup()
                        .addComponent(maleLastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maleLastName))
                    .addGroup(maleInfoPanelLayout.createSequentialGroup()
                        .addComponent(maleNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maleName)))
                .addContainerGap())
        );
        maleInfoPanelLayout.setVerticalGroup(
            maleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleLastNameLabel)
                    .addComponent(maleLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleNameLabel)
                    .addComponent(maleName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        femaleInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("F_PANEL_WIFE"))); // NOI18N

        femaleLastNameLabel.setText(bundle.getString("F_LABEL_LASTNAME")); // NOI18N

        femaleNameLabel.setText(bundle.getString("F_LABEL_NAME")); // NOI18N

        femaleLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        femaleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout femaleInfoPanelLayout = new javax.swing.GroupLayout(femaleInfoPanel);
        femaleInfoPanel.setLayout(femaleInfoPanelLayout);
        femaleInfoPanelLayout.setHorizontalGroup(
            femaleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(femaleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(femaleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(femaleInfoPanelLayout.createSequentialGroup()
                        .addComponent(femaleLastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(femaleLastName))
                    .addGroup(femaleInfoPanelLayout.createSequentialGroup()
                        .addComponent(femaleNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(femaleName)))
                .addContainerGap())
        );
        femaleInfoPanelLayout.setVerticalGroup(
            femaleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(femaleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(femaleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(femaleLastNameLabel)
                    .addComponent(femaleLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(femaleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(femaleNameLabel)
                    .addComponent(femaleName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title.setText(getTitle());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(female)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(title)
                                .addGap(0, 0, 0)
                                .addComponent(footer)
                                .addGap(0, 0, 0)
                                .addComponent(min)
                                .addGap(0, 0, 0)
                                .addComponent(separator)
                                .addGap(0, 0, 0)
                                .addComponent(max))
                            .addComponent(actNumberLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(yearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(year))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(actNumber))
                    .addComponent(maleInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(femaleInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maleInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(actNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(year))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footer)
                    .addComponent(min)
                    .addComponent(separator)
                    .addComponent(max)
                    .addComponent(title))
                .addGap(20, 20, 20))
        );

        suggestPanel.setOpaque(false);
        suggestPanel.setLayout(null);

        suggestList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        suggestList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suggestListMouseClicked(evt);
            }
        });
        suggestList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                suggestListKeyPressed(evt);
            }
        });
        suggestScroll.setViewportView(suggestList);

        suggestPanel.add(suggestScroll);
        suggestScroll.setBounds(70, 30, 258, 130);

        layers.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layers.setLayer(suggestPanel, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout layersLayout = new javax.swing.GroupLayout(layers);
        layers.setLayout(layersLayout);
        layersLayout.setHorizontalGroup(
            layersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layersLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(suggestPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layersLayout.setVerticalGroup(
            layersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(suggestPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(layers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(layers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchCaretUpdate
        int dot = evt.getDot();
        suggestScroll.setVisible(false);
        if (dot > 0) try {
            String searchQuery = search.getText(0, dot).toLowerCase();
            List<String> sugg = new ArrayList<>();
            for (MarriageIndex i: indices.getLoaded()) {
                String[] words = searchQuery.split(" "); //NOI18N
                Person person = male.isSelected()? i.male: i.female;
                if (person.getLastName().toLowerCase().startsWith(words[0])) {
                    if (words.length == 1)
                        sugg.add(i.toLabelString(male.isSelected()));
                    else {
                        String nameQuery = ""; //NOI18N
                        for (int in = 1; in < words.length; in++) {
                            nameQuery += words[in];
                            if (in < words.length-1) nameQuery += " "; //NOI18N
                        }
                       if (person.getName().toLowerCase().startsWith(nameQuery))
                            sugg.add(i.toLabelString(male.isSelected()));
                    }
                }
            }
            if (sugg.isEmpty()) return;
            suggestList.setListData(sugg.toArray(new String[sugg.size()]));
            Rectangle searchB = search.getBounds();
            suggestScroll.setLocation(searchB.x, searchB.y + searchB.height);
            int height = suggestList.getCellBounds(0,0).height
                    *suggestList.getModel().getSize()+5;
            if (height > suggestList.getCellBounds(0,0).height*8+5) {
                height = suggestList.getCellBounds(0,0).height*8+5;
            }
            suggestScroll.setSize(searchB.width, height);
            suggestScroll.setVisible(true);
        } catch (BadLocationException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_searchCaretUpdate

    private void suggestListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suggestListMouseClicked
        if (evt.getClickCount() < 2) return;
        setForm();
    }//GEN-LAST:event_suggestListMouseClicked

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            suggestList.setSelectedIndex(suggestList.getFirstVisibleIndex());
            suggestList.grabFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            suggestList.setSelectedIndex(suggestList.getLastVisibleIndex());
            suggestList.grabFocus();
        }
    }//GEN-LAST:event_searchKeyPressed

    private void suggestListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suggestListKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER
                && suggestList.getSelectedIndex() >= 0) {
            setForm();
        }
    }//GEN-LAST:event_suggestListKeyPressed

    private void setForm() {
        suggestScroll.setVisible(false);
        search.setText(""); //NOI18N
        try {
            setForm(indices.find(suggestList.getSelectedValue(),
                    male.isSelected()));
        } catch (ObjectNotFoundException ex) {
            JOptionPane.showMessageDialog(this,
                "Wystąpił błąd, ponieważ nie znaleziono indeksu.\n\n"
                        + "Błąd typu:\n\t" + ex,
                "Nie znaleziono indeksu", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void setForm(MarriageIndex i) {
        setForm(i.male.getLastName(), i.male.getName(),
                i.female.getLastName(), i.female.getName(), i.getAct(), i.year);
    }
    
    public void setForm(String maleLastName, String maleName,
            String femaleLastName, String femaleName, String act, int year) {
        this.maleLastName.setText(maleLastName);
        this.maleName.setText(maleName);
        this.femaleLastName.setText(femaleLastName);
        this.femaleName.setText(femaleName);
        this.actNumber.setText(act);
        if (year >= 0) this.year.setText(year + ""); //NOI18N
        else this.year.setText(""); //NOI18N
    }
    
    public final void resetForm() {
        setForm("", "", "", "", "", -1); //NOI18N
    }
    
    public final void setFooter(String min, String max) {
        this.min.setText(min);
        this.max.setText(max);
    }
    
    public void setSuggestionList(String[] suggestions) {
        suggestList.setListData(suggestions);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        if (Integer.parseInt(args[0]) == OPTION_ZA) EventQueue.invokeLater(() -> {
            new IndexResearchFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actNumber;
    private javax.swing.JLabel actNumberLabel;
    private javax.swing.JRadioButton female;
    private javax.swing.JPanel femaleInfoPanel;
    private javax.swing.JLabel femaleLastName;
    private javax.swing.JLabel femaleLastNameLabel;
    private javax.swing.JLabel femaleName;
    private javax.swing.JLabel femaleNameLabel;
    private javax.swing.JLabel footer;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLayeredPane layers;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton male;
    private javax.swing.JPanel maleInfoPanel;
    private javax.swing.JLabel maleLastName;
    private javax.swing.JLabel maleLastNameLabel;
    private javax.swing.JLabel maleName;
    private javax.swing.JLabel maleNameLabel;
    private javax.swing.JLabel max;
    private javax.swing.JLabel min;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel separator;
    private javax.swing.ButtonGroup sex;
    private javax.swing.JList<String> suggestList;
    private javax.swing.JPanel suggestPanel;
    private javax.swing.JScrollPane suggestScroll;
    private javax.swing.JLabel title;
    private javax.swing.JLabel year;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
