/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.koder95.ip;

import javax.swing.JFrame;
import static pl.koder95.ip.Main.OPTION_OC;
import static pl.koder95.ip.Main.OPTION_BI;
import static pl.koder95.ip.Main.OPTION_ZA;
import static pl.koder95.ip.Main.OPTION_ZM;

/**
 *
 * @author Kamil
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = -5330474306601981277L;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public void openIndexResearch(int option) {
        JFrame win;
        switch (option) {
            case OPTION_ZA: win = new pl.koder95.ip.marriage.IndexResearchFrame(); break;
            default: win = new IndexBrowserFrame(option);
        }
        win.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionOC = new javax.swing.JButton();
        optionBI = new javax.swing.JButton();
        optionZA = new javax.swing.JButton();
        optionZM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(pl.koder95.ip.Main.BUNDLE.getString("F_TITLE")); // NOI18N
        setIconImage(pl.koder95.ip.Main.FAVICON);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        optionOC.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionOC.setText("<html><center>l i b e r<br/>baptizatorum</center></html>"); // NOI18N
        optionOC.setMargin(new java.awt.Insets(5, 5, 5, 5));
        optionOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionOCActionPerformed(evt);
            }
        });
        getContentPane().add(optionOC);

        optionBI.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionBI.setText("<html><center>l i b e r<br/>confirmatorum</center></html>"); // NOI18N
        optionBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBIActionPerformed(evt);
            }
        });
        getContentPane().add(optionBI);

        optionZA.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionZA.setText("<html><center>l i b e r<br/>matrimoniorum</center></html>"); // NOI18N
        optionZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionZAActionPerformed(evt);
            }
        });
        getContentPane().add(optionZA);

        optionZM.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionZM.setText("<html><center>l i b e r<br/>defunctorum</center></html>"); // NOI18N
        optionZM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionZMActionPerformed(evt);
            }
        });
        getContentPane().add(optionZM);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void optionOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionOCActionPerformed
        openIndexResearch(OPTION_OC);
    }//GEN-LAST:event_optionOCActionPerformed

    private void optionBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBIActionPerformed
        openIndexResearch(OPTION_BI);
    }//GEN-LAST:event_optionBIActionPerformed

    private void optionZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionZAActionPerformed
        openIndexResearch(OPTION_ZA);
    }//GEN-LAST:event_optionZAActionPerformed

    private void optionZMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionZMActionPerformed
        openIndexResearch(OPTION_ZM);
    }//GEN-LAST:event_optionZMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton optionBI;
    private javax.swing.JButton optionOC;
    private javax.swing.JButton optionZA;
    private javax.swing.JButton optionZM;
    // End of variables declaration//GEN-END:variables
}
