/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.koder95.ip.u161203;

import pl.koder95.ip.*;
import javax.swing.JFrame;

/**
 *
 * @author Kamil
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionOC = new javax.swing.JButton();
        optionBI = new javax.swing.JButton();
        optionZA = new javax.swing.JButton();
        optionZM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(pl.koder95.ip.Main.BUNDLE.getString("F_TITLE")); // NOI18N
        setIconImage(pl.koder95.ip.Main.FAVICON);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        optionOC.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionOC.setText("<html><center>l i b e r<br/>baptizatorum</center></html>"); // NOI18N
        optionOC.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(optionOC);

        optionBI.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionBI.setText("<html><center>l i b e r<br/>confirmatorum</center></html>"); // NOI18N
        getContentPane().add(optionBI);

        optionZA.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionZA.setText("<html><center>l i b e r<br/>matrimoniorum</center></html>"); // NOI18N
        getContentPane().add(optionZA);

        optionZM.setFont(new java.awt.Font("Parchment", 1, 75)); // NOI18N
        optionZM.setText("<html><center>l i b e r<br/>defunctorum</center></html>"); // NOI18N
        getContentPane().add(optionZM);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton optionBI;
    private javax.swing.JButton optionOC;
    private javax.swing.JButton optionZA;
    private javax.swing.JButton optionZM;
    // End of variables declaration//GEN-END:variables
}
